// <auto-generated />
using System;
using HBKPlatform.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBKPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219214552_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.HasSequence("HbkBaseEntitySequence");

            modelBuilder.Entity("HBKPlatform.Database.ClientPractitioner", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int>("TenancyId")
                        .HasColumnType("integer")
                        .HasColumnName("tenancy_id");

                    b.HasKey("ClientId", "PractitionerId")
                        .HasName("pk_client_practitioners");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_client_practitioners_practitioner_id");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_client_practitioners_tenancy_id");

                    b.ToTable("client_practitioners", (string)null);
                });

            modelBuilder.Entity("HBKPlatform.Database.HbkBaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("nextval('\"HbkBaseEntitySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("CreateActioner")
                        .HasColumnType("text")
                        .HasColumnName("create_actioner");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("ModifyActioner")
                        .HasColumnType("text")
                        .HasColumnName("modify_actioner");

                    b.Property<int>("TenancyId")
                        .HasColumnType("integer")
                        .HasColumnName("tenancy_id");

                    b.HasKey("Id");

                    b.HasIndex("TenancyId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("HBKPlatform.Database.Tenancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<int>("LicenceStatus")
                        .HasColumnType("integer")
                        .HasColumnName("licence_status");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_name");

                    b.Property<string>("OrgTagline")
                        .HasColumnType("text")
                        .HasColumnName("org_tagline");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tenancies");

                    b.ToTable("tenancies", (string)null);
                });

            modelBuilder.Entity("HBKPlatform.Database.Timeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_timeslots");

                    b.ToTable("timeslots", (string)null);
                });

            modelBuilder.Entity("HBKPlatform.Database.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("login_count");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("TenancyId")
                        .HasColumnType("integer")
                        .HasColumnName("tenancy_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_asp_net_users_tenancy_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("application_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("HBKPlatform.Database.Appointment", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int?>("RoomReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("room_reservation_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("integer")
                        .HasColumnName("timeslot_id");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_id");

                    b.Property<int>("WeekNum")
                        .HasColumnType("integer")
                        .HasColumnName("week_num");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_appointments_client_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_appointments_practitioner_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_appointments_room_id");

                    b.HasIndex("RoomReservationId")
                        .HasDatabaseName("ix_appointments_room_reservation_id");

                    b.HasIndex("TimeslotId")
                        .HasDatabaseName("ix_appointments_timeslot_id");

                    b.HasIndex("TreatmentId")
                        .HasDatabaseName("ix_appointments_treatment_id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("HBKPlatform.Database.Attribute", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.ToTable("attributes");
                });

            modelBuilder.Entity("HBKPlatform.Database.Client", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forename");

                    b.Property<string>("Img")
                        .HasColumnType("text")
                        .HasColumnName("img");

                    b.Property<int>("PracticeId")
                        .HasColumnType("integer")
                        .HasColumnName("practice_id");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<int>("Title")
                        .HasColumnType("integer")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasIndex("PracticeId")
                        .HasDatabaseName("ix_clients_practice_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_clients_user_id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("HBKPlatform.Database.ClientMessage", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("DateOpened")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_opened");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_body");

                    b.Property<int>("MessageOrigin")
                        .HasColumnType("integer")
                        .HasColumnName("message_origin");

                    b.Property<int>("MessageStatusClient")
                        .HasColumnType("integer")
                        .HasColumnName("message_status_client");

                    b.Property<int>("MessageStatusPractitioner")
                        .HasColumnType("integer")
                        .HasColumnName("message_status_practitioner");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int?>("PreviousMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("previous_message_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_messages_client_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_client_messages_practitioner_id");

                    b.HasIndex("PreviousMessageId")
                        .HasDatabaseName("ix_client_messages_previous_message_id");

                    b.ToTable("client_messages");
                });

            modelBuilder.Entity("HBKPlatform.Database.ClientRecord", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_priority");

                    b.Property<string>("NoteBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_body");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int>("RecordVisibility")
                        .HasColumnType("integer")
                        .HasColumnName("record_visibility");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_client_records_appointment_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_records_client_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_client_records_practitioner_id");

                    b.ToTable("client_records");
                });

            modelBuilder.Entity("HBKPlatform.Database.Clinic", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("ManagerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasIndex("ManagerUserId")
                        .HasDatabaseName("ix_clinics_manager_user_id");

                    b.ToTable("clinics");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practice", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<int?>("LeadPractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_practitioner_id");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasIndex("LeadPractitionerId")
                        .IsUnique()
                        .HasDatabaseName("ix_practices_lead_practitioner_id");

                    b.ToTable("practices");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practitioner", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("ClientBio")
                        .HasColumnType("text")
                        .HasColumnName("client_bio");

                    b.Property<string>("ClinicBio")
                        .HasColumnType("text")
                        .HasColumnName("clinic_bio");

                    b.Property<string>("Credentials")
                        .HasColumnType("text")
                        .HasColumnName("credentials");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forename");

                    b.Property<string>("GmcNumber")
                        .HasColumnType("text")
                        .HasColumnName("gmc_number");

                    b.Property<string>("Img")
                        .HasColumnType("text")
                        .HasColumnName("img");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("PracticeId")
                        .HasColumnType("integer")
                        .HasColumnName("practice_id");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<int>("Title")
                        .HasColumnType("integer")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasIndex("PracticeId")
                        .HasDatabaseName("ix_practitioners_practice_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_practitioners_user_id");

                    b.ToTable("practitioners");
                });

            modelBuilder.Entity("HBKPlatform.Database.Room", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .HasColumnType("text")
                        .HasColumnName("img");

                    b.Property<double>("PricePerUse")
                        .HasColumnType("double precision")
                        .HasColumnName("price_per_use");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_rooms_clinic_id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("HBKPlatform.Database.RoomAttribute", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_room_attributes_attribute_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_attributes_room_id");

                    b.ToTable("room_attributes");
                });

            modelBuilder.Entity("HBKPlatform.Database.RoomReservation", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer")
                        .HasColumnName("clinic_id");

                    b.Property<string>("ClinicNote")
                        .HasColumnType("text")
                        .HasColumnName("clinic_note");

                    b.Property<string>("PracticeNote")
                        .HasColumnType("text")
                        .HasColumnName("practice_note");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_status");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("integer")
                        .HasColumnName("timeslot_id");

                    b.Property<int>("WeekNum")
                        .HasColumnType("integer")
                        .HasColumnName("week_num");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_room_reservations_clinic_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_room_reservations_practitioner_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_reservations_room_id");

                    b.HasIndex("TimeslotId")
                        .HasDatabaseName("ix_room_reservations_timeslot_id");

                    b.ToTable("room_reservations");
                });

            modelBuilder.Entity("HBKPlatform.Database.Setting", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("value2");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("HBKPlatform.Database.TimeslotAvailability", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<int>("Entity")
                        .HasColumnType("integer")
                        .HasColumnName("entity");

                    b.Property<int>("Interlude")
                        .HasColumnType("integer")
                        .HasColumnName("interlude");

                    b.Property<bool>("IsIndefinite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_indefinite");

                    b.Property<int?>("PractitionerId")
                        .HasColumnType("integer")
                        .HasColumnName("practitioner_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("integer")
                        .HasColumnName("timeslot_id");

                    b.Property<int>("WeekNum")
                        .HasColumnType("integer")
                        .HasColumnName("week_num");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_timeslot_availability_practitioner_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_timeslot_availability_room_id");

                    b.HasIndex("TimeslotId")
                        .HasDatabaseName("ix_timeslot_availability_timeslot_id");

                    b.ToTable("timeslot_availability");
                });

            modelBuilder.Entity("HBKPlatform.Database.Treatment", b =>
                {
                    b.HasBaseType("HBKPlatform.Database.HbkBaseEntity");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .HasColumnType("text")
                        .HasColumnName("img");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TreatmentRequestability")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_requestability");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("HBKPlatform.Database.ClientPractitioner", b =>
                {
                    b.HasOne("HBKPlatform.Database.Client", "Client")
                        .WithMany("ClientPractitioners")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_practitioners_hbk_base_entity_client_id");

                    b.HasOne("HBKPlatform.Database.Practitioner", "Practitioner")
                        .WithMany("ClientPractitioners")
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_practitioners_hbk_base_entity_practitioner_id");

                    b.HasOne("HBKPlatform.Database.Tenancy", "Tenancy")
                        .WithMany()
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_practitioners_tenancies_tenancy_id");

                    b.Navigation("Client");

                    b.Navigation("Practitioner");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("HBKPlatform.Database.HbkBaseEntity", b =>
                {
                    b.HasOne("HBKPlatform.Database.Tenancy", "Tenancy")
                        .WithMany()
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("HBKPlatform.Database.User", b =>
                {
                    b.HasOne("HBKPlatform.Database.Tenancy", "Tenancy")
                        .WithMany()
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_users_tenancies_tenancy_id");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HBKPlatform.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HBKPlatform.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("HBKPlatform.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HBKPlatform.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("HBKPlatform.Database.Appointment", b =>
                {
                    b.HasOne("HBKPlatform.Database.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_clients_client_id");

                    b.HasOne("HBKPlatform.Database.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_practitioners_practitioner_id");

                    b.HasOne("HBKPlatform.Database.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .HasConstraintName("fk_appointments_rooms_room_id");

                    b.HasOne("HBKPlatform.Database.RoomReservation", "RoomReservation")
                        .WithMany()
                        .HasForeignKey("RoomReservationId")
                        .HasConstraintName("fk_appointments_room_reservations_room_reservation_id");

                    b.HasOne("HBKPlatform.Database.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_timeslots_timeslot_id");

                    b.HasOne("HBKPlatform.Database.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_treatments_treatment_id");

                    b.Navigation("Client");

                    b.Navigation("Practitioner");

                    b.Navigation("Room");

                    b.Navigation("RoomReservation");

                    b.Navigation("Timeslot");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("HBKPlatform.Database.Client", b =>
                {
                    b.HasOne("HBKPlatform.Database.Practice", "Practice")
                        .WithMany("Clients")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_practices_practice_id");

                    b.HasOne("HBKPlatform.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_clients_asp_net_users_user_id");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HBKPlatform.Database.ClientMessage", b =>
                {
                    b.HasOne("HBKPlatform.Database.Client", null)
                        .WithMany("ClientMessages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_messages_clients_client_id");

                    b.HasOne("HBKPlatform.Database.Practitioner", null)
                        .WithMany("ClientMessages")
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_messages_practitioners_practitioner_id");

                    b.HasOne("HBKPlatform.Database.ClientMessage", "PreviousMessage")
                        .WithMany()
                        .HasForeignKey("PreviousMessageId")
                        .HasConstraintName("fk_client_messages_client_messages_previous_message_id");

                    b.Navigation("PreviousMessage");
                });

            modelBuilder.Entity("HBKPlatform.Database.ClientRecord", b =>
                {
                    b.HasOne("HBKPlatform.Database.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("fk_client_records_appointments_appointment_id");

                    b.HasOne("HBKPlatform.Database.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_records_clients_client_id");

                    b.HasOne("HBKPlatform.Database.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_records_practitioners_practitioner_id");

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("HBKPlatform.Database.Clinic", b =>
                {
                    b.HasOne("HBKPlatform.Database.User", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinics_asp_net_users_manager_user_id");

                    b.Navigation("ManagerUser");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practice", b =>
                {
                    b.HasOne("HBKPlatform.Database.Practitioner", "LeadPractitioner")
                        .WithOne()
                        .HasForeignKey("HBKPlatform.Database.Practice", "LeadPractitionerId")
                        .HasConstraintName("fk_practices_practitioners_lead_practitioner_id");

                    b.Navigation("LeadPractitioner");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practitioner", b =>
                {
                    b.HasOne("HBKPlatform.Database.Practice", "Practice")
                        .WithMany("Practitioners")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practitioners_practices_practice_id");

                    b.HasOne("HBKPlatform.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_practitioners_asp_net_users_user_id");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HBKPlatform.Database.Room", b =>
                {
                    b.HasOne("HBKPlatform.Database.Clinic", "Clinic")
                        .WithMany("Rooms")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_clinics_clinic_id");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HBKPlatform.Database.RoomAttribute", b =>
                {
                    b.HasOne("HBKPlatform.Database.Attribute", "Attribute")
                        .WithMany("RoomAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_attributes_attributes_attribute_id");

                    b.HasOne("HBKPlatform.Database.Room", "Room")
                        .WithMany("RoomAttributes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_attributes_rooms_room_id");

                    b.Navigation("Attribute");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HBKPlatform.Database.RoomReservation", b =>
                {
                    b.HasOne("HBKPlatform.Database.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_reservations_clinics_clinic_id");

                    b.HasOne("HBKPlatform.Database.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_reservations_practitioners_practitioner_id");

                    b.HasOne("HBKPlatform.Database.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_reservations_rooms_room_id");

                    b.HasOne("HBKPlatform.Database.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_reservations_timeslots_timeslot_id");

                    b.Navigation("Clinic");

                    b.Navigation("Practitioner");

                    b.Navigation("Room");

                    b.Navigation("Timeslot");
                });

            modelBuilder.Entity("HBKPlatform.Database.TimeslotAvailability", b =>
                {
                    b.HasOne("HBKPlatform.Database.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .HasConstraintName("fk_timeslot_availability_practitioners_practitioner_id");

                    b.HasOne("HBKPlatform.Database.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .HasConstraintName("fk_timeslot_availability_rooms_room_id");

                    b.HasOne("HBKPlatform.Database.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timeslot_availability_timeslots_timeslot_id");

                    b.Navigation("Practitioner");

                    b.Navigation("Room");

                    b.Navigation("Timeslot");
                });

            modelBuilder.Entity("HBKPlatform.Database.Attribute", b =>
                {
                    b.Navigation("RoomAttributes");
                });

            modelBuilder.Entity("HBKPlatform.Database.Client", b =>
                {
                    b.Navigation("ClientMessages");

                    b.Navigation("ClientPractitioners");
                });

            modelBuilder.Entity("HBKPlatform.Database.Clinic", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practice", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Practitioners");
                });

            modelBuilder.Entity("HBKPlatform.Database.Practitioner", b =>
                {
                    b.Navigation("ClientMessages");

                    b.Navigation("ClientPractitioners");
                });

            modelBuilder.Entity("HBKPlatform.Database.Room", b =>
                {
                    b.Navigation("RoomAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
